name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node: [ 18 ]
    runs-on: ${{matrix.os}}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.NPM_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - name: Install
        run: pnpm i
      - name: Compile
        run: npm run compile
      - name: Run tests
        uses: coactions/setup-xvfb@v1
        with:
          run: pnpm run coverage

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.NPM_TOKEN }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v3.0.0
      - run: pnpm i
      - name: Publish tagged release to npm
        run: pnpm run publish:release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}